### ISSUE TITLE
Forks that throw immediately try to abort their parent while the parent is still running

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection.js#26]
Take the following case:

```js
import { fork } from 'effection';

fork(function* outer() {
  fork(function* inner() {
    throw new Error('boom!');
  });
});
```

This aborts with an error as expected, but the error is not super useful, since it does not actually contain the original exception, but rather a complaint about incorrect `Generator` states:

```
TypeError: Generator is already running
    at outer.throw (<anonymous>)
    at thunk.iterator (fork.js:70:30)
    at Fork.fn [as enter] (fork.js:181:14)
    at Fork.enter (fork.js:158:23)
    at Fork.thunk (fork.js:70:12)
    at Fork.join (fork.js:152:7)
    at Fork.join [as finalize] (fork.js:196:19)
    at Fork.finalize [as thunk] (fork.js:172:12)
    at Fork.thunk [as resume] (fork.js:91:12)
    at Fork.resume (fork.js:89:12)
```

This is because when an exception occurs in a `Fork`, we catch it and then progressively call `throw` on the parent `Fork`s all the way up to the root fork (provided that nobody catches it). There problem occurs here where the `outer` generator is actually part of the parent stack of the `inner`. 

This is an invalid operation on a generator that is currently running, which `outer` still is. In other words, it has not yielded yet.

While this does not change the logic of a program in the sense that it will still fail at the right point, it nevertheless _hides the root cause_ of the exception by replacing the actual error with the `TypeError: Generator is already running`

It's not obvious what the solution is, but some of the ones discussed so far are:

1. make all forks happen in the next tick of the run-loop. That way, the parent is guaranteed to continue to a yieldpoint before the exception is thrown and so `parent.throw()` will be a valid operation
2. detect when the parent is currently on the call stack, and re-throw the error to allow it to percolate to the parent after child finalization.
3. collect forked children on a queue which is then resumed in-order when the parent reaches the next yieldpoint.

We need to research these possible approaches, as well as identify others before coming to a conclusion.

**Comment by jnicklas** [comment]
I do think we need to find a solution to this as soon as possible. This issue is making debugging pretty painful, since it is very tricky to get the actual source of an exception. I was just facing such a situation where I'd spent half an hour trying to figure out why something was failing. I patched effection locally to run `resume` in the next tick and the error became obvious immediately.

The most natural solution to me feels like running on the next tick. I did just look into this a bit, and while the change itself is easy, changing the effection test suite is quite a bit of work.
