### ISSUE TITLE
Rename Execution->Task?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection.js#61]
The thing that we are calling Execution which is currently returned by `fork` (but probably won't be eventually) is called a `Task` by many systems which are similar to Effection, e.g. Rust's standardlib and ember-concurrency.

It's both a shorter and less awkward name, and also imo reflects the nature of what it represents better.

**Comment by cowboyd** [comment]
#57 splits `Execution (Fork)` into two objects, an `Context` and a `Controller`. Among other things, this alleviates some of the concerns that we had with

```ts
let child: Context = yield fork();
```

because now (at least in the typings) `child` is just an opaque object representing the execution context of the fork, and its only public method it has is `halt()`;

At least in Ember Concurrency, `Task` is a much higher level concept that involves queuing and cancellation behavior. For example: run this operation, don't let more than 10 instances of it be running concurrently, and in the event that the buffer of ten is full, cancel the oldest task to make room for the new one.

I'm amenable to renaming it, but first curious what you think about `Context`

**Comment by jnicklas** [comment]
Either is fine to me really, maybe Task sounds a bit more specific than Context, which really could mean anything.

Here is some good info on the Rust concept of a task:

https://rust-lang.github.io/async-book/02_execution/03_wakeups.html

**Comment by cowboyd** [comment]
I need to wrap my head around the Rust example since I'm not super fluent, but it does seem like there is also the concept of context there too?

My current preference for `Context` lies in the prediction that it will be used as a place to represent the tree and also hold state for user-created operations and effects. In other words, "operation takes place in a context"

Still, `Context` is vague and perhaps over-worn. Another word to consider would be"Frame", as in "stack frame", or a scratchpad to hold information about execution (although technically in this case it would be a tree frame)

**Comment by cowboyd** [comment]
I like neither `Execution` or `ExecutionContext`, and `Task` feels more natural especially with the `spawn` primitive. However, I don't think we want to piece-meal this. 

The API thus far has been artisanally and organically grown, but it's probably time to not just consider renaming one interface, but also renaming all the methods, and properties as well.

I've opened up #66 for a wider discussion of what renaming to `Task` (or something else) would entail.
